import { DataSource } from "typeorm";

export const AppDataSource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 3306,
  username: "erpdb",
  password: "123456",
  database: "sup_ticketing_tool",
  entities: [__dirname + "/../**/*.entity{.ts,.js}"], // Path to your entities
  migrations: [__dirname + "/../migrations/*{.ts,.js}"], // Path to your migrations
  synchronize: true, // Use only in development; false in production
});


AppDataSource.initialize()
  .then(() => {
    console.log("Data Source has been initialized!");
  })
  .catch((err) => {
    console.error("Error during Data Source initialization:", err);
  });


  // "migration:generate": "npm run build && npm run typeorm -- migration:generate -d ./dist/data-source.js src/migrations/AutoGeneratedMigration",
// npm run typeorm -- migration:generate -d ./dist/data-source.js ./src/migrations/CreateEmployeeAndDepartmentTables
// npm run typeorm -- migration:generate -d ./dist/data-source.js ./src/migrations/CreateEmployeeAndDepartmentTables


// npm run migration:generate
// npm run migration:run
//npm run typeorm -- migration:run -d ./src/data-source.ts
